<?php ?>
<h2><?= $block->getSubTitle() ?></h2>
<p> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente quae accusantium, asperiores tempore inventore vel similique architecto recusandae nemo esse suscipit accusamus. Cupiditate ducimus accusantium aliquam. Ad voluptate animi nisi.</p>

<?= $block->getChildHtml('layout_note')?>

<?= $block->getNodeHtml() ?>

<?= $block->getChildHtml('cms_block_example') ?>